Update Metasploit

diff --git a/MSFinstaller b/MSFinstaller
--- a/MSFinstaller
+++ b/MSFinstaller
@@ -27,11 +27,10 @@ MOR="\e[0;49;95m"
 FORT="\e[0m"
 declare -r XYELOW='\e[7;100;33m'
 MSF=$PWD
-MSFVERSION=6.1.20
-declare -r TERMUX_MD5SUM_MSF=ac0ba73faf5bee0d2cf53c0492649cf9
+MSFVERSION=6.1.19
+declare -r TERMUX_MD5SUM_MSF=c8801f5be679714cc9a981eb12c40553
 NOOB=metasploit-framework
 NAME="$MSFVERSION.tar.gz"
-RUBY="JZCmp"
 declare -r CONFIG="$PREFIX/etc/MSF"
 msfpath=$PREFIX/opt/$NOOB
 cd $HOME
@@ -86,9 +85,17 @@ BannerRuby
 #
 # Ruby 3.0.2
 #
-#wget2 --tries=30  https://git.io/JZCmp -q -P $TMPDIR
-#chmod +x $TMPDIR/$RUBY
-#$TMPDIR/./$RUBY
+BRed='\033[1;31m'
+[[ $(uname -m) = 'arm' ]] && printf "$BRed[ The script is not yet available for ARM ]\n\n\033[0m" && exit 1
+[[ -f $PREFIX/bin/ruby ]] && Ruby_Version=`ruby -v | cut -d' ' -f2`
+echo ${A%%.*}
+[[ $(uname -m) = 'aarch64' ]] && [[ ${Ruby_Version%%.*} -ne 2 ]] && printf "[ Downloading ruby 2.7.2 ]\n\n" && if ! curl --fail --retry 5 --retry-connrefused --retry-delay 5 --location \
+	-o ruby.deb https://bit.ly/3GE2lck;
+then
+	printf "[ Error de descarga ]\n\n"
+	rm -rf ruby.deb
+fi
+[[ ! -f ruby.deb ]] && printf "[ Ruby not found! ]\n\n" && exit 1
 #
 #
 clear
@@ -96,14 +103,21 @@ banner
 mkdir -p $PREFIX/opt/$NOOB
 mkdir -p $CONFIG
 # Download and update
-[[ ! -f $CONFIG/$NAME ]] && Info_msf $1 && rm -rf $CONFIG/* && wget2 --progress=bar  https://github.com/rapid7/metasploit-framework/archive/refs/tags/$MSFVERSION.tar.gz --tries=30 -P $CONFIG
-
+[[ ! -f $CONFIG/$NAME ]] && Info_msf $1 && rm -rf $CONFIG/* && if ! curl --fail --retry 5 --retry-connrefused --retry-delay 5 --location \
+	-O "https://github.com/rapid7/metasploit-framework/archive/refs/tags/$MSFVERSION.tar.gz";
+then 
+	printf "\n${RED}[✗] ${WHITE}Incorrect download | check your internet ${RED}[✗]${FORT}\n\n"
+	rm -rf $CONFIG/$NAME
+	exit 0
+fi
+mv -f ~/${NAME} $CONFIG
 until [[ $(md5sum $CONFIG/$NAME | awk '{print $1}') = "$TERMUX_MD5SUM_MSF" ]]
 do
 	printf "\n${RED}[✗] ${WHITE}Incorrect download | check your internet ${RED}[✗]${FORT}\n\n"
 	rm -rf $CONFIG/$NAME
 	exit 0
 done
+printf "[ \033[1;33mExtracting files'\033[0m' ]\n\n"
 tar zxf "$CONFIG/$NAME" --strip-components=1 \
         -C "$PREFIX"/opt/$NOOB
 #
